"""initial schema

Revision ID: 0001
Revises:
Create Date: 2025-01-01 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("material_source_dir", sa.String(1024), nullable=False),
        sa.Column("aspect_ratio", sa.String(10), nullable=True, server_default="9:16"),
        sa.Column("resolution", sa.String(20), nullable=True, server_default="1080x1920"),
        sa.Column(
            "index_status",
            sa.Enum("PENDING", "INDEXING", "READY", "FAILED", name="indexstatus"),
            nullable=True,
            server_default="PENDING",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "storyboards",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("project_id", sa.String(36), nullable=False),
        sa.Column("style", sa.String(100), nullable=False),
        sa.Column("total_duration_sec", sa.Integer(), nullable=False),
        sa.Column("bgm_mood", sa.String(200), nullable=True),
        sa.Column("raw_prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("project_id", sa.String(36), nullable=False),
        sa.Column("file_name", sa.String(512), nullable=False),
        sa.Column("file_path", sa.String(1024), nullable=False),
        sa.Column("file_type", sa.String(20), nullable=False),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column("qdrant_point_id", sa.String(36), nullable=True),
        sa.Column("indexed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shots",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("storyboard_id", sa.String(36), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("shot_type", sa.String(50), nullable=False),
        sa.Column("camera_motion", sa.String(50), nullable=True, server_default="静态"),
        sa.Column("transition", sa.String(50), nullable=True, server_default="硬切"),
        sa.Column("mood_words", sa.JSON(), nullable=True, server_default="[]"),
        sa.ForeignKeyConstraint(["storyboard_id"], ["storyboards.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "material_matches",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("storyboard_id", sa.String(36), nullable=False),
        sa.Column("shot_index", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.String(36), nullable=False),
        sa.Column("clip_start_sec", sa.Float(), nullable=True, server_default="0.0"),
        sa.Column("clip_end_sec", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True, server_default="0.0"),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("user_selected", sa.Boolean(), nullable=True, server_default="false"),
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["storyboard_id"], ["storyboards.id"],),
        sa.ForeignKeyConstraint(["material_id"], ["materials.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edit_tasks",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("project_id", sa.String(36), nullable=False),
        sa.Column("storyboard_id", sa.String(36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "PROCESSING", "RENDERING", "COMPLETED", "FAILED", name="taskstatus"),
            nullable=True,
            server_default="QUEUED",
        ),
        sa.Column("progress_pct", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("estimated_remaining_sec", sa.Integer(), nullable=True),
        sa.Column("output_path", sa.String(1024), nullable=True),
        sa.Column("error_message", sa.String(2048), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"],),
        sa.ForeignKeyConstraint(["storyboard_id"], ["storyboards.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("edit_tasks")
    op.drop_table("material_matches")
    op.drop_table("shots")
    op.drop_table("materials")
    op.drop_table("storyboards")
    op.drop_table("projects")
    op.execute("DROP TYPE IF EXISTS indexstatus")
    op.execute("DROP TYPE IF EXISTS taskstatus")
    # ### end Alembic commands ###
